In [3]:
!pip install kagglehub

Collecting kagglehub
  Using cached kagglehub-0.3.13-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: packaging in /opt/anaconda3/envs/ecom-ws/lib/python3.11/site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /opt/anaconda3/envs/ecom-ws/lib/python3.11/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /opt/anaconda3/envs/ecom-ws/lib/python3.11/site-packages (from kagglehub) (2.32.5)
Collecting tqdm (from kagglehub)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/ecom-ws/lib/python3.11/site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/ecom-ws/lib/python3.11/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/ecom-ws/lib/python3.11/site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/ecom-ws/lib/python3.11/site-packages (from requests->kagglehub) (2026.1.4)
Using cached kagglehub-0.3.13-py3-none-any.whl (68 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, kagglehub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [kagglehub]
Successfully installed kagglehub-0.3.13 tqdm-4.67.1

In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mkechinov/ecommerce-behavior-data-from-multi-category-store")

print("Path to dataset files:", path)

/opt/anaconda3/envs/ecom-ws/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/olaf/.cache/kagglehub/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store/versions/8

In [21]:
df_test = pd.read_csv(path+'/2019-Nov.csv')
df_test

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,NaN,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882655,electronics.smartphone,xiaomi,183.27,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2
...,...,...,...,...,...,...,...,...,...
67501974,2019-11-30 23:59:58 UTC,view,15700137,2053013559733912211,NaN,NaN,277.74,532714000,02b4131c-0112-4231-aafa-ceaa08e77c1b
67501975,2019-11-30 23:59:58 UTC,view,28719425,2053013565639492569,apparel.shoes,baden,62.81,545223467,734c5eef-0742-4f8b-9d22-48f75b0bc359
67501976,2019-11-30 23:59:59 UTC,view,1004833,2053013555631882655,electronics.smartphone,samsung,167.03,557794415,6fecf566-ebb0-4e70-a243-cdc13ce044cb
67501977,2019-11-30 23:59:59 UTC,view,2701706,2053013563911439225,appliances.kitchen.refrigerators,samsung,566.27,531607492,368ddc8b-5db9-40fb-b7ff-b6582a1192c0
67501978,2019-11-30 23:59:59 UTC,view,1004233,2053013555631882655,electronics.smartphone,apple,1312.52,579969851,90aca71c-ed8a-4670-866a-761ebacb732d

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lower, trim, regexp_replace, to_timestamp, to_date, hour, date_format, when, lit
from pyspark.sql.types import StructType, StructField, StringType, LongType, DoubleType
from pathlib import Path
import glob

# This function reads all csv files in the path
def read_csv_files(spark, pattern: str,schema):
    files = sorted(glob.glob(pattern))
    if not files:
        raise FileNotFoundError(f"No files matched: {pattern}")
    files = [str(Path(f).resolve()) for f in files]
    return spark.read.option("header", True).schema(schema).csv(files)

# Create a Spark session to run spark sql
spark = (
    SparkSession.builder
    .appName("ecom-etl")
    .master("local[*]")
    .config("spark.driver.memory", "8g")
    .config("spark.sql.shuffle.partitions", "200")
    .config("spark.sql.files.maxPartitionBytes", 128 * 1024 * 1024)
    .getOrCreate()
)

spark.conf.set("spark.sql.session.timeZone", "UTC")
spark.sparkContext.setLogLevel("WARN")

raw_path = "data/raw/*.csv"
out_path = "data/processed/events_parquet"

schema = StructType([
    StructField("event_time", StringType(), True),
    StructField("event_type", StringType(), True),
    StructField("product_id", LongType(), True),
    StructField("category_id", LongType(), True),
    StructField("category_code", StringType(), True),
    StructField("brand", StringType(), True),
    StructField("price", DoubleType(), True),
    StructField("user_id", LongType(), True),
    StructField("user_session", StringType(), True),
])
df = read_csv_files(spark, raw_path ,schema )

def norm_str(c):
    x = lower(trim(col(c)))
    return when(x.isNull() | (x == "") | (x == "nan"), lit(None)).otherwise(x)

ALLOWED = ["view", "cart", "remove_from_cart", "purchase"]

clean = (
    df
    .withColumn("event_type", lower(trim(col("event_type"))))
    .withColumn("brand", norm_str("brand"))
    .withColumn("category_code", norm_str("category_code"))
    .withColumn("user_session", trim(col("user_session")))
    .withColumn("event_time_str", regexp_replace(col("event_time"), r"\s+UTC$", ""))
    .withColumn("event_time", to_timestamp(col("event_time_str"), "yyyy-MM-dd HH:mm:ss"))
    .withColumn("event_date", to_date(col("event_time")))
    .withColumn("event_hour", hour(col("event_time")))
    .withColumn("event_month", date_format(col("event_time"), "yyyy-MM"))
    .filter(col("event_time").isNotNull())
    .filter(col("event_date").isNotNull())
    .filter(col("event_type").isin(ALLOWED))
    .filter(col("price").isNotNull() & (col("price") >= 0) & (col("price") < 1_000_000))
    .drop("event_time_str")
)

# Repartitioning to multiple parquets files 
clean = clean.repartition(120, "event_date")

(clean.write
 .mode("overwrite")
 .partitionBy("event_date")
 .parquet(out_path)
)

spark.stop()
print("Wrote parquet to:", out_path)

In [9]:
import glob
matches = glob.glob(raw_path)
if not matches:
    raise FileNotFoundError(f"No files matched raw_path={raw_path}. CWD={os.getcwd()}")
print("Matched files:", matches[:5], "...")

Matched files: ['data/raw/2019-Nov.csv', 'data/raw/2019-Oct.csv'] ...

In [15]:
events_path = "data/processed/events_parquet"

# 选一天（换成你实际有的日期，比如 2019-11-01）
one_day_path = f"{events_path}/event_date=2019-11-01"

df_day = spark.read.parquet(one_day_path)
df_day.show(20, truncate=False)
df_day.printSchema()
df_day.count()

+-------------------+----------+----------+-------------------+--------------------------------+--------+------+---------+------------------------------------+----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code                   |brand   |price |user_id  |user_session                        |event_hour|event_month|
+-------------------+----------+----------+-------------------+--------------------------------+--------+------+---------+------------------------------------+----------+-----------+
|2019-10-31 20:00:00|view      |1003461   |2053013555631882655|electronics.smartphone          |xiaomi  |489.07|520088904|4d3b30da-a5e4-49df-b1a8-ba5943f1dd33|0         |2019-11    |
|2019-10-31 20:00:00|view      |5000088   |2053013566100866035|appliances.sewing_machine       |janome  |293.65|530496790|8e5f4f83-366c-4f70-860e-ca7417414283|0         |2019-11    |
|2019-10-31 20:00:01|view      |17302664  |2053013553853497655|NULL                            |creed   |28.31 |561587266|755422e7-9040-477b-9bd2-6a6e8fd97387|0         |2019-11    |
|2019-10-31 20:00:01|view      |3601530   |2053013563810775923|appliances.kitchen.washer       |lg      |712.87|518085591|3bfb58cd-7892-48cc-8020-2f17e6de6e7f|0         |2019-11    |
|2019-10-31 20:00:01|view      |1004775   |2053013555631882655|electronics.smartphone          |xiaomi  |183.27|558856683|313628f1-68b8-460d-84f6-cec7a8796ef2|0         |2019-11    |
|2019-10-31 20:00:01|view      |1306894   |2053013558920217191|computers.notebook              |hp      |360.09|520772685|816a59f3-f5ae-4ccd-9b23-82aa8c23d33c|0         |2019-11    |
|2019-10-31 20:00:01|view      |1306421   |2053013558920217191|computers.notebook              |hp      |514.56|514028527|df8184cc-3694-4549-8c8c-6b5171877376|0         |2019-11    |
|2019-10-31 20:00:02|view      |15900065  |2053013558190408249|NULL                            |rondell |30.86 |518574284|5e6ef132-4d7c-4730-8c7f-85aa4082588f|0         |2019-11    |
|2019-10-31 20:00:02|view      |12708937  |2053013553559896355|NULL                            |michelin|72.72 |532364121|0a899268-31eb-46de-898d-09b2da950b24|0         |2019-11    |
|2019-10-31 20:00:02|view      |1004258   |2053013555631882655|electronics.smartphone          |apple   |732.07|532647354|d2d3d2c6-631d-489e-9fb5-06f340b85be0|0         |2019-11    |
|2019-10-31 20:00:03|view      |17200570  |2053013559792632471|furniture.living_room.sofa      |NULL    |437.33|518780843|aa806835-b14c-45af-9538-cd4d1849be3e|0         |2019-11    |
|2019-10-31 20:00:03|view      |2701517   |2053013563911439225|appliances.kitchen.refrigerators|NULL    |155.11|518427361|c89b0d96-247f-4044-9c91-bb5f38c6af9b|0         |2019-11    |
|2019-10-31 20:00:03|view      |16700260  |2053013559901684381|furniture.kitchen.chair         |NULL    |31.64 |566255262|173d7b72-1db7-4638-8207-be8148bf3c9f|0         |2019-11    |
|2019-10-31 20:00:04|view      |34600011  |2060981320581906480|NULL                            |NULL    |20.54 |512416379|4dfe2c67-e537-4dc2-ae69-0b65263db091|0         |2019-11    |
|2019-10-31 20:00:05|view      |4600658   |2053013563944993659|appliances.kitchen.dishwasher   |samsung |411.83|526595547|aab33a9a-29c3-4d50-84c1-8a2bc9256104|0         |2019-11    |
|2019-10-31 20:00:06|view      |24900193  |2053013562183385881|NULL                            |NULL    |1.09  |512651494|f603c815-f51a-46fe-9404-cb586e35edaf|0         |2019-11    |
|2019-10-31 20:00:07|view      |27400066  |2053013563391345499|NULL                            |NULL    |8.55  |551061950|3f6112f1-5695-4e88-bb0a-49f9e36658ff|0         |2019-11    |
|2019-10-31 20:00:07|view      |5100503   |2053013553375346967|NULL                            |xiaomi  |22.68 |520037415|f54fa96a-f3f2-43ac-99a4-fcb2a449dd36|0         |2019-11    |
|2019-10-31 20:00:07|view      |1004566   |2053013555631882655|electronics.smartphone          |huawei  |164.84|566265908|52c2c76c-b79e-4794-86ff-badc76d35f5a|0         |2019-11    |
|2019-10-31 20:00:08|view      |1307115   |2053013558920217191|computers.notebook              |hp      |411.59|514028527|df8184cc-3694-4549-8c8c-6b5171877376|0         |2019-11    |
+-------------------+----------+----------+-------------------+--------------------------------+--------+------+---------+------------------------------------+----------+-----------+
only showing top 20 rows
root
 |-- event_time: timestamp (nullable = true)
 |-- event_type: string (nullable = true)
 |-- product_id: long (nullable = true)
 |-- category_id: long (nullable = true)
 |-- category_code: string (nullable = true)
 |-- brand: string (nullable = true)
 |-- price: double (nullable = true)
 |-- user_id: long (nullable = true)
 |-- user_session: string (nullable = true)
 |-- event_hour: integer (nullable = true)
 |-- event_month: string (nullable = true)

1445360

In [23]:
ud = pd.read_parquet("data/processed/user_daily")
sf = pd.read_parquet("data/processed/session_funnel")

# 例：daily_high_events
ud["events_day"] = ud["views"] + ud["carts"] + ud["removes"] + ud["purchases"]
thr = ud["events_day"].quantile(0.999)
anoms = ud[ud["events_day"] >= thr].sort_values("events_day", ascending=False).head(200)

KeyboardInterrupt:

In [5]:
import pandas as pd
df = pd.read_csv("/Users/olaf/bin/ecommerce_project/data/outputs/tables/anomalous_users.csv/part-00000-9a0ace6b-8f72-4711-9905-1516cd761358-c000.csv")
df[df['anomaly_type'] == 'funnel_mismatch']

,user_id,as_of_date,anomaly_type,score,evidence
600,512875426,2019-11-29,funnel_mismatch,709.0,"sum_carts_cnt=709, sum_purchases_cnt=0, mismat..."
601,513824664,2019-11-15,funnel_mismatch,299.0,"sum_carts_cnt=299, sum_purchases_cnt=0, mismat..."
602,521558076,2019-11-10,funnel_mismatch,292.0,"sum_carts_cnt=292, sum_purchases_cnt=0, mismat..."
603,515642515,2019-11-14,funnel_mismatch,237.0,"sum_carts_cnt=237, sum_purchases_cnt=0, mismat..."
604,513754375,2019-11-17,funnel_mismatch,203.0,"sum_carts_cnt=203, sum_purchases_cnt=0, mismat..."
...,...,...,...,...,...
778,516723213,2019-11-16,funnel_mismatch,50.0,"sum_carts_cnt=50, sum_purchases_cnt=0, mismatc..."
779,571337651,2019-11-16,funnel_mismatch,50.0,"sum_carts_cnt=50, sum_purchases_cnt=0, mismatc..."
780,517885000,2019-11-12,funnel_mismatch,50.0,"sum_carts_cnt=50, sum_purchases_cnt=0, mismatc..."
781,572070840,2019-11-21,funnel_mismatch,50.0,"sum_carts_cnt=50, sum_purchases_cnt=0, mismatc..."
782,515318076,2019-10-15,funnel_mismatch,50.0,"sum_carts_cnt=50, sum_purchases_cnt=0, mismatc..."

In [3]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lower, trim, regexp_replace, to_timestamp, to_date, hour, date_format, when, lit
from pyspark.sql.types import StructType, StructField, StringType, LongType, DoubleType
from pathlib import Path
import glob

spark = (
    SparkSession.builder
    .master("local[*]")
    .appName("check-sizes")
    .getOrCreate()
)

print(spark.read.parquet("data/processed/user_daily").count())
print(spark.read.parquet("data/processed/session_funnel").count())

15095144
23017602